version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: backup-log-to-s3
    main: ./main.go
    binary: backup-log-to-s3
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: backup-log-to-s3
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew tap (disabled for now - requires HOMEBREW_TAP_GITHUB_TOKEN)
# brews:
#   - name: backup-log-to-s3
#     tap:
#       owner: signity-inc
#       name: homebrew-tap
#       token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#     url_template: "https://github.com/signity-inc/backup-log-to-s3/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
#     folder: Formula
#     homepage: "https://github.com/signity-inc/backup-log-to-s3"
#     description: "A command-line tool for backing up log files to Amazon S3 with intelligent date-based filtering."
#     license: "MIT"
#     skip_upload: auto
#     dependencies:
#       - name: go
#         type: build

# Linux packages
nfpms:
  - id: backup-log-to-s3
    package_name: backup-log-to-s3
    vendor: Signity Inc.
    homepage: https://github.com/signity-inc/backup-log-to-s3
    maintainer: Signity Inc. <dev@signity.co.jp>
    description: A command-line tool for backing up log files to Amazon S3 with intelligent date-based filtering.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    section: utils
    priority: optional
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - backup-log-to-s3
    bindir: /usr/bin

# Docker images (disabled for now - uncomment when ready)
# dockers:
#   - image_templates:
#       - "ghcr.io/signity-inc/backup-log-to-s3:{{ .Version }}"
#       - "ghcr.io/signity-inc/backup-log-to-s3:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - --label=org.opencontainers.image.title={{ .ProjectName }}
#       - --label=org.opencontainers.image.description={{ .ProjectName }}
#       - --label=org.opencontainers.image.url=https://github.com/signity-inc/backup-log-to-s3
#       - --label=org.opencontainers.image.source=https://github.com/signity-inc/backup-log-to-s3
#       - --label=org.opencontainers.image.version={{ .Version }}
#       - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#       - --label=org.opencontainers.image.revision={{ .FullCommit }}
#       - --label=org.opencontainers.image.licenses=MIT

release:
  draft: false
  prerelease: auto
  name_template: "Release {{ .Tag }}"