name: Setup GitHub Pages

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Create and push gh-pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create orphan branch
          git checkout --orphan gh-pages
          
          # Remove all files from staging
          git rm -rf .
          
          # Create initial structure
          mkdir -p rpm/releases
          echo "# backup-log-to-s3 Repository" > README.md
          
          # Commit and push
          git add .
          git commit -m "Initial gh-pages setup"
          git push origin gh-pages --force